version: '3'

services:

  postgres:
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: env_manager
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: envmanager_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8085:80"
    depends_on: 
      - postgres
  
  phoenix:
    build: .
    ports:
      - "8080:8080"
    depends_on: 
      - postgres