version: '3'

services:
  postgres:
    build:
      context: ./postgres
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: envmanager_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8085:80"
    depends_on: 
      - postgres
  
  phoenix:
    build: .
    entrypoint: ["/app", "-is-cluster-ready=false"]
    ports:
      - "8080:8080"
    depends_on: 
      - postgres
      - pgadmin

  frontend:
    image: setimo/phoenix-frontend:0.0.11
    env_file:
      - .env.compose
    container_name: frontend
    ports:
      - "3030:80"