apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix-envmanager-backend-db
  namespace: operators
  labels:
    operator-controller: phoenix-envmanager-backend-db
    app.kubernetes.io/name: phoenix-backend-db
spec:
  selector:
    matchLabels:
      operator-controller: phoenix-envmanager-backend-db
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: phoenix-backend-db
      labels:
        operator-controller: phoenix-envmanager-backend-db
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - image: phoenix-backend-db:latest
        name: phoenix-backend-db
        ports:
          - containerPort: 5432
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
    volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    operator-controller: phoenix-envmanager-backend-db
    app.kubernetes.io/name: phoenix-backend-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
        


      